### ISSUE TITLE
getting weight mismatch error

### ISSUE THREAD

**Issue by JohnsWillson** [ualsg/Global-road-network-patterns#1]
while using the procalculator i am getting this error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 2
      1 pc = prob_calculator(channeles=3)  # Define a prob_calculator that deal with images of three channeles
----> 2 pc.load_model(model_path)  # Load the road network classification model
      3 grids = pc.getProb(grid_path, image_path, save_path)

File F:\M Plan\Sem 4\DRP\Tools\Global roads\Global roads\morphoindex_generator_v2.py:332, in prob_calculator.load_model(self, model_path)
    330 elif self.channeles == 6:
    331     self.model = Build_model(config).build_mymodel()
--> 332 self.model.load_weights(model_path)

File D:\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    119     filtered_tb = _process_traceback_frames(e.__traceback__)
    120     # To get the full stack trace, call:
    121     # `keras.config.disable_traceback_filtering()`
--> 122     raise e.with_traceback(filtered_tb) from None
    123 finally:
    124     del filtered_tb

File D:\anaconda3\Lib\site-packages\keras\src\backend\common\variables.py:222, in KerasVariable.assign(self, value)
    220 value = self._convert_to_tensor(value, dtype=self.dtype)
    221 if not shape_equal(value.shape, self.shape):
--> 222     raise ValueError(
    223         "The shape of the target variable and "
    224         "the shape of the target value in "
    225         "`variable.assign(value)` must match. "
    226         f"variable.shape={self.value.shape}, "
    227         f"Received: value.shape={value.shape}. "
    228         f"Target variable: {self}"
    229     )
    230 if in_stateless_scope():
    231     scope = get_stateless_scope()

ValueError: The shape of the target variable and the shape of the target value in `variable.assign(value)` must match. variable.shape=(512, 4), Received: value.shape=(512, 6). Target variable: <KerasVariable shape=(512, 4), dtype=float32, path=dense/kernel>

**Comment by chenww1219** [comment]
@JohnsWillson Thanks for using our codes. This issue seems to indicate a mismatch between the pre-trained model and the defined model architecture. We have two versions of models: one for 4-class classification and the other for 6-class classification. You should have a matching file named _train_class_idx.txt_ in the main folder, indicating the specific classes. We have uploaded the 6-class version to the respository. To use the 6-class model, please download it to your local and make sure you download the 6-class model as well.
